### ISSUE TITLE
Shockwave blows up all entities include paintings and item frames

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#4]
The shockwave power blows up all entities that the wave touches, including paintings and item frames on the wall.

This can destroy buildings decorated with these items.

**Comment by RecursiveG** [comment]
Maybe it's a better option to enable users disable this "feature" from config, instead of simply remove it from the code?

**Comment by phoenixlzx** [comment]
Sure is. Add a config option like `ignore_entities: []` should be ok.

**Comment by Taiterio** [comment]
Fixed in commit 09d02f142598560e7daec84b96afb29929e51f44; the solution I used is to attach metadata to paintings and itemframes before the explosion is created. Afterwards, in the HangingBreakEvent I check if the entity that broke has this metadata, cancelling the event appropriately. I furthermore protect those entities from the velocity that shockwave gives to affected entities.

This solution is not as general as the one suggested by @phoenixlzx, but I think that it should be fine since the problem was restricted to the hanging entities. If there are any other entities affected by the shockwave that should not be, just say so :)

**Comment by phoenixlzx** [comment]
I tested item frames on the wall and the problem still exists, but with a chance, not all item frames blowed up.

**Comment by RecursiveG** [comment]
@phoenixlzx I think it's because the explosion range is too large and affected those entities which are not been protected. There's no good way to protect paintings from one particular explosion AFAIK. Maybe users should use EssentialProtect or WorldGuard if they don't want these entities been destroyed by explosions.

**Comment by phoenixlzx** [comment]
@RecursiveG No way to control the explosion range? I think a small explosion will cast the effect but not to destroy entities.

**Comment by RecursiveG** [comment]
Of course you can, it's the `power` param of `PowerRumble`. A more powerful explosion means a larger range. I think there's no way to perform a powerful explosion but limited within a small range.

**Comment by phoenixlzx** [comment]
Got it, confused with `range` param.

Maybe we should note this on the wiki page.

**Comment by Taiterio** [comment]
That's something I forgot to take into consideration then. It its easy to get the range of the explosion, I could increase the range that the paintings and hanging frames are protected in.

**Comment by RecursiveG** [comment]
By referring the code of Forge, I found that an explosion will affect the entities within the radius of two times of it's `power`.
I increased the protection radius and hope this will fix this issue. See c506f6d
